### ISSUE TITLE
Rollbar library is out of date

### ISSUE THREAD

**Issue by bvisness** [flowdee/rollbar#6]
The bundled version of Rollbar's PHP library is out of date. The plugin is on version 0.15.0 but Rollbar's library is now up to version 0.18.2. (See the [changelog](https://github.com/rollbar/rollbar-php/blob/master/CHANGELOG.md))

**Comment by flowdee** [comment]
thanks for the reminder @bvisness 👍  going to update asap

**Comment by flowdee** [comment]
Library updated to the lastest v0.18.2 release. Thanks for the request!
